### ISSUE TITLE
Processing findFont Broken

### ISSUE THREAD

**Issue by catieterrey** [BiocomputeLab/bsim#5]
Hi there,

I am trying to run BSim on Windows 10 64 bit. The program compiles successfully using `ant compile`.

However, when I run my simulation using the following input, I get an error. The program runs completely fine if it is compiled and run using IntelliJ IDEA. This problem only happens when running using the command line.

```
java -cp .;../../lib/core.jar;../../lib/vecmath.jar;../../lib/objimport.jar;../../lib/bsim-osp.jar;../../lib/jcommander-1.49-SNAPSHOT.jar       Fall2020/NeighbourInteractions'
```

The error I get is:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at processing.core.PFont.loadFonts(Unknown Source)
        at processing.core.PFont.findFont(Unknown Source)
        at bsim.draw.BSimP3DDrawer.<init>(Unknown Source)
        at Fall2020.NeighbourInteractions$2.<init>(Unknown Source)
        at Fall2020.NeighbourInteractions.run(Unknown Source)
        at Fall2020.NeighbourInteractions.main(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
        at java.base/java.lang.String.substring(String.java:1903)
        at processing.core.PApplet.<clinit>(Unknown Source)
        ... 6 more
```

The class Fall2020.NeighbourInteractions is derived from BSimChenOscillator. I have just removed the chemical fields and set it so that there is only one type of bacteria. 

It seems the issue is with Processing 1.5, which is 9 years old now and could use an update. However, since the program runs just fine in IntelliJ IDEA I am very confused. Changing the font from MS Trebuchet to another font does not fix the problem.

**Comment by antmatyjajo** [comment]
Hi, thanks for reporting this! 

I will look into it. Which version of Java/JDK are you using? 

> It seems the issue is with Processing 1.5, which is 9 years old now and could use an update

Good point, I'll look into updating that. You're right though that this is probably not the root of this issue if everything runs fine from intellij...

**Comment by antmatyjajo** [comment]
Hello,

Sorry but unfortunately I am unable to reproduce this problem locally (windows 10x64, java 1.8)...

I will try to update to a new version of the processing lib at some point if I can. In the meantime it would be useful to know a couple of things - 

Are you definitely using the same version of java in the termianal as is being used by intellij?

Does the problem also occur for you with the included simulations, e.g., the BSimSimplest or BSimTutorial (or even BSimChenOscillator, since you based your code on that one)? Or does it only happen with your code?

**Comment by catieterrey** [comment]
Hello,

Thank you for the ideas, I indeed was using a different compiler in the terminal. Before fixing the compiler, I tried running BSimSimplest and it gave the same error which seems to be a problem with BSimP3DDrawer.

I've managed to make the program run by using openJDK14, which is the compiler that IntelliJ IDEA uses.

It is still strange that compiling and running the code using a different compiler does not work. I have tried jdk-15 as well as jdk  8 and have had no success. It may be worth looking into whether the code is compatible with different JDK versions. 

Thanks!

**Comment by antmatyjajo** [comment]
Hi,

Thanks for the update, that's very interesting (and slightly strange). The code has, up until now, been working fine with different versions of the JDK, although I have to admit I didn't try running it with a JDK newer than 12. Indeed on my machine I can run everything fine using JDK 8, which conversely doesn't work for you.

If you have a moment, could you list the complete sequence of commands that you use when you see a failure? Maybe for BSimSimplest, for example. And finally the exact versions of java (and ant + whichever other commands you run during the pipeline). Would be super helpful as I am having no luck replicating this and it would be nice to fix the problem if possible...

Thanks!
